on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-west-3'

name: deploy testing

run-name: Deploy to testing env by @${{ github.actor }}

env:
  ENV_NAME: testing

jobs:
  deploy:
    name: Deploy to AWS - testing
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: testing
      region: ${{ inputs.region }}
    secrets: inherit
