on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-west-3'

name: deploy staging

run-name: Deploy to staging env by @${{ github.actor }}

env:
  ENV_NAME: staging

jobs:
  deploy:
    name: Deploy to AWS - staging
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      region: ${{ inputs.region }}
    secrets: inherit
