on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-west-3'

name: deploy production

run-name: Deploy to production env by @${{ github.actor }}

env:
  ENV_NAME: production

jobs:
  deploy:
    name: Deploy to AWS - production
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
      region: ${{ inputs.region }}
    secrets: inherit
