on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-west-3'

name: deploy development

run-name: Deploy to development env by @${{ github.actor }}

env:
  ENV_NAME: development

jobs:
  deploy:
    name: Deploy to AWS - development
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: development
      region: ${{ inputs.region }}
    secrets: inherit
